--CREATE TABLE chat_user (
--    id BIGINT PRIMARY KEY,
--    email VARCHAR(255) UNIQUE NOT NULL,
--    username VARCHAR(50) UNIQUE,
--    password_hash VARCHAR(255) NOT NULL,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);

CREATE TABLE chat_room (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE room_member (
    room_id BIGINT NOT NULL REFERENCES chat_room(id) ON DELETE CASCADE,
    member_id UUID NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, member_id)
);


